### ISSUE TITLE
knockoff_filter.forward gives different results on every run.

### ISSUE THREAD

**Issue by wasifmasood** [amspector100/knockpy#2]
I have taken the example code from the doc page. 

```
# Create a random covariance matrix for X
import numpy as np
import knockpy
import warnings

np.random.seed(123)
n = 300 # number of data points
p = 500  # number of features
Sigma = knockpy.dgp.AR1(p=p, rho=0.5) # Stationary AR1 process with correlation 0.5

# Sample X
X = np.random.multivariate_normal(mean=np.zeros(p), cov=Sigma, size=(n,))

# Create random sparse coefficients
beta = knockpy.dgp.create_sparse_coefficients(p=p, sparsity=0.1)
y = np.dot(X, beta) + np.random.randn(n)

from knockpy.knockoff_filter import KnockoffFilter
kfilter = KnockoffFilter(
    ksampler='gaussian',
    fstat='lasso',
)

```

But every time I rerun the forward function, I get very different answers. I dont see any seed parameter here either so that I could rerun the code in loop myself to get some stable results. Can you pls recommend me what to do to handle this challenge?

```

# Flags of whether each feature was rejected
rejections = kfilter.forward(
    X=X,
    y=y,
    Sigma=Sigma,
    fdr=0.1 # desired level of false discovery rate control
)
# Check the number of discoveries we made
power = np.dot(rejections, beta != 0) / (beta != 0).sum()
fdp = np.around(100*np.dot(rejections, beta == 0) / rejections.sum())
print(f"The knockoff filter has discovered {100*power}% of the non-nulls with a FDP of {fdp}%")
```

**Comment by wasifmasood** [comment]
For example, one ran give me the following results:

`The knockoff filter has discovered 100.0% of the non-nulls with a FDP of 18.0%`

Shouldn't this be less than 10% as per the fdr value in the forward function?

**Comment by amspector100** [comment]
Hi, 

To get stable results, try including the line ``np.random.seed(123)`` just before running ``kfilter.forward.`` You need to set the seed in the same cell that you run ``kfilter.forward`` otherwise if you re-run the cell, it won't set the seed properly.  Let me know if this still doesn't work. 

It is important to note that knockoffs is a randomized procedure and thus its output will depend on the seed---this is an active area of research, and a  very recent paper (https://arxiv.org/abs/2205.15461) has proposed a solution if you're interested. This solution will probably be integrated into knockpy in the next major update, but that may not be for a month or so.

For your second question, there is a difference between the FDR and the FDP. The FDP (false discovery proportion) is equal to the number of false discoveries divided by the number of total discoveries. It's impossible for _any_ statistical method to control the FDP, because that would require knowing which discoveries are true or false, which is unknown by assumption! Instead, knockoffs controls the FDR, which is the expectation of the FDP. This means that on average, the FDP will be below 10%, but it may fluctuate above / below 10% depending on the random seed and the particular realization of a dataset. However, if you sample a dataset from the same data-generating process many times, knockoffs provably controls the FDR.
